language : node_js
node_js :
  - stable
  - lts/*
  - 6.9
env:
  - WEBPACK_VERSION=1
  - WEBPACK_VERSION=2
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=4
install:
  - npm i
  - npm rm webpack
  - npm i -D webpack@$WEBPACK_VERSION
script:
  - npm run build
  - npm test